spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/zxl #url
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp

